rancher/install-docker

1.10.3.sh
1.11.2.sh
1.12.1.sh
1.12.2.sh
1.12.3.sh
1.12.4.sh
1.12.5.sh
1.12.6.sh
1.13.1.sh
17.03.0.sh
17.03.1.sh
17.04.0.sh
17.05.0.sh

Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>
looks like I need to get a fix into docker-machine to use the `engine-install-url` if present

switch Docker engine to the requested version

---

17.03.0.sh
17.03.1.sh
17.03.2.sh

Add workaround for RHEL based distro (https://github.com/docker/for-linux/issues/20)
Tested on Ubuntu 1404/1604, CentOS 7, Fedora 25 and Debian 9

Update 17.03 to updated scripts and add 17.03.2

---

17.04.0.sh
17.05.0.sh

Copied from 17.03, changed stable to edge.

Syncing edge releases to new scripts

---

1.13.0.sh
17.03.0.sh
17.03.1.sh
17.03.2.sh
17.06.0.sh

Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

fix rancheros docker engine switch

---

18.03.0.sh
18.03.1.sh
18.06.0.sh
18.06.1.sh
18.06.2.sh
18.06.3.sh
18.09.0.sh
18.09.1.sh
18.09.2.sh
18.09.3.sh
18.09.4.sh

https://github.com/rancher/rancher/issues/19161

Enable arm64/aarch64 for Ubuntu/RHEL

---

18.06.0.sh
18.06.1.sh
18.06.2.sh
18.06.3.sh
18.09.0.sh
18.09.1.sh
18.09.2.sh
18.09.3.sh
18.09.4.sh
18.09.5.sh
18.09.6.sh

Add support for docker versions 18.03.* and 18.06.*

Add debian buster support

---

19.03.0.sh
19.03.1.sh
19.03.2.sh
19.03.3.sh
19.03.4.sh
19.03.5.sh

https://github.com/rancher/rancher/issues/24529

Add repo to provide for container-selinux on RHEL

---

19.03.5.sh

This commit PR adds support for versioned docker installs in SLES
Related Issue: https://github.com/rancher/rancher/issues/25342

Add SLES support

---

18.09.0.sh
18.09.1.sh
18.09.2.sh
18.09.3.sh
18.09.4.sh
18.09.5.sh
18.09.6.sh
18.09.7.sh
18.09.8.sh
18.09.9.sh
19.03.0.sh
19.03.1.sh
19.03.10.sh
19.03.11.sh
19.03.12.sh
19.03.13.sh
19.03.2.sh
19.03.3.sh
19.03.4.sh
19.03.5.sh
19.03.7.sh
19.03.8.sh
19.03.9.sh

https://github.com/rancher/rancher/issues/29246

Fix setting correct repo path for EL like OS

---

18.09.0.sh
18.09.1.sh
18.09.2.sh
18.09.3.sh
18.09.4.sh
18.09.5.sh
18.09.6.sh
18.09.7.sh
18.09.8.sh
18.09.9.sh
19.03.0.sh
19.03.1.sh
19.03.10.sh
19.03.11.sh
19.03.12.sh
19.03.13.sh
19.03.2.sh
19.03.3.sh
19.03.4.sh
19.03.5.sh
19.03.7.sh
19.03.8.sh
19.03.9.sh

https://github.com/rancher/rancher/issues/27691

Add addons repo for Oracle Linux

---

19.03.13.sh

https://github.com/rancher/rancher/issues/23045
Also move the installation of the `pre-req` as `yum-utils` is required to be able to invoke `yum-config-manager`...
Signed-off-by: Chris Kim <oats87g@gmail.com>

Add initial el8 support to install-docker script

---

17.03.0.sh
17.03.1.sh
17.03.2.sh

This only affects 17.03.x, changes verified by QA.
Final fix for https://github.com/rancher/rancher/issues/29749

Install working selinux package for 17.03

---

dist/20.10.2.sh
dist/20.10.3.sh
pkg/20.10.2/20.10.2.diff
pkg/20.10.2/config.sh
pkg/20.10.3/20.10.3.diff
pkg/20.10.3/config.sh
scripts/generate
scripts/test

Issue https://github.com/rancher/rancher/issues/31132

Fix 20.10.sh to properly install on oracle linux 7

---

dist/20.10.2.sh
dist/20.10.3.sh
pkg/20.10.2/20.10.2.diff
pkg/20.10.3/20.10.3.diff

Adding extra names to `rhel-7-server-extras-rpms` repo

Fix 20.10.sh script to properly install at all rhel 7 images

---

scripts/add-new-version
scripts/test-docker

* Adds comparing `Client.Version` to the requested version so we know we installed the right version
* Adds replacing the `VERSION` env var to the newly added install script on `add-new-version`

New version fixes

---

.drone.yml
scripts/test
scripts/validate

Related to https://github.com/rancher/rancher/issues/41096

add link checker to validate script

---

.github/workflows/workflow.yaml

Fixed incorrect double quotes which was causing build failures.

Fix extra quotes

---

.github/workflows/workflow.yaml

Updated secret retrieval path as discussed with EIO. 
SURE-7991

Fix secret retrieval

---

.github/workflows/workflow.yaml

Change Cache-Control to lowercase
SURE-7791

Fix headers for upload-cloud-storage job

---

.github/workflows/add_new_versions.yml

- Add id-token write permission

Add id-token write permission
